<?php
/**
 * Template part for displaying single post content
 *
 * @link https://developer.wordpress.org/themes/basics/template-hierarchy/
 *
 * @package wp_modern_starter_main_theme
 */

?>

<article id="post-<?php the_ID(); ?>" <?php post_class('post-article'); ?>>
    <header class="post-article__header">
        <div class="container">
            <?php if ( function_exists('yoast_breadcrumb') ) : ?>
                <nav class="post-article__breadcrumb">
                    <?php yoast_breadcrumb(); ?>
                </nav>
            <?php endif; ?>
            
            <?php
            $categories = get_the_category();
            if ( ! empty( $categories ) ) :
            ?>
                <div class="post-article__category"><?php echo esc_html( $categories[0]->name ); ?></div>
            <?php endif; ?>
            
            <h1 class="post-article__title"><?php the_title(); ?></h1>
            
            <?php if ( has_excerpt() ) : ?>
                <div class="post-article__subtitle"><?php echo wp_kses_post( get_the_excerpt() ); ?></div>
            <?php endif; ?>
            
            <div class="post-article__meta">
                <div class="post-article__author-info">
                    <?php echo get_avatar( get_the_author_meta( 'ID' ), 48, '', '', array( 'class' => 'post-article__author-avatar' ) ); ?>
                    <div class="post-article__author-details">
                        <span class="post-article__author-name"><?php the_author(); ?></span>
                        <span class="post-article__author-title"><?php echo esc_html( get_the_author_meta( 'description' ) ?: 'Site Author' ); ?></span>
                    </div>
                </div>
                <div class="post-article__stats">
                    <div class="post-article__stat">
                        <i class="fas fa-calendar"></i>
                        <time datetime="<?php echo esc_attr( get_the_date( 'c' ) ); ?>"><?php echo esc_html( get_the_date() ); ?></time>
                    </div>
                    <div class="post-article__stat">
                        <i class="fas fa-clock"></i>
                        <span><?php echo esc_html( wp_modern_starter_estimated_reading_time() ); ?> min read</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="post-article__content">
        <div class="container">
            <div class="post-article__content-wrapper">
                <div class="post-article__body">
                    <?php if ( has_post_thumbnail() ) : ?>
                        <div class="post-article__featured-image">
                            <?php the_post_thumbnail( 'full', array( 'class' => 'img-fluid' ) ); ?>
                        </div>
                    <?php endif; ?>
                    
                    <div class="post-article__content-text">
                        <?php
                        the_content(
                            sprintf(
                                wp_kses(
                                    /* translators: %s: Name of current post. Only visible to screen readers */
                                    __( 'Continue reading<span class="screen-reader-text"> "%s"</span>', 'wp-modern-starter' ),
                                    array(
                                        'span' => array(
                                            'class' => array(),
                                        ),
                                    )
                                ),
                                wp_kses_post( get_the_title() )
                            )
                        );

                        wp_link_pages(
                            array(
                                'before' => '<div class="page-links">' . esc_html__( 'Pages:', 'wp-modern-starter' ),
                                'after'  => '</div>',
                            )
                        );
                        ?>
                    </div>
                    
                    <?php if ( get_the_tags() ) : ?>
                        <div class="post-article__tags">
                            <span class="post-article__tags-label"><?php esc_html_e( 'Tags:', 'wp-modern-starter' ); ?></span>
                            <?php the_tags( '', ', ', '' ); ?>
                        </div>
                    <?php endif; ?>
                </div>

                <aside class="post-article__sidebar">
                    <div class="post-article__toc">
                        <h3 class="post-article__toc-title">Table of Contents</h3>
                        <ul class="post-article__toc-list">
                            <!-- TOC will be generated by JavaScript -->
                        </ul>
                    </div>

                    <?php
                    $related_posts = wp_modern_starter_get_related_posts( get_the_ID(), 3 );
                    if ( ! empty( $related_posts ) ) :
                    ?>
                        <div class="post-article__related">
                            <h3 class="post-article__related-title">Related Articles</h3>
                            <?php foreach ( $related_posts as $related_post ) : ?>
                                <div class="post-article__related-item">
                                    <h4 class="post-article__related-item-title"><a href="<?php echo esc_url( get_permalink( $related_post->ID ) ); ?>"><?php echo esc_html( get_the_title( $related_post->ID ) ); ?></a></h4>
                                    <span class="post-article__related-item-date"><?php echo esc_html( get_the_date( '', $related_post->ID ) ); ?></span>
                                </div>
                            <?php endforeach; ?>
                        </div>
                    <?php endif; ?>

                    <div class="post-article__author-bio">
                        <?php echo get_avatar( get_the_author_meta( 'ID' ), 80, '', '', array( 'class' => 'post-article__author-bio-avatar' ) ); ?>
                        <div class="post-article__author-bio-content">
                            <h4 class="post-article__author-bio-name"><?php the_author(); ?></h4>
                            <p class="post-article__author-bio-description"><?php echo esc_html( get_the_author_meta( 'description' ) ?: 'Senior WordPress Developer with 8+ years of experience building scalable web applications. Passionate about performance optimization and modern development practices.' ); ?></p>
                            <div class="post-article__author-bio-social">
                                <!-- First: LinkedIn -->
                                <?php if ( get_the_author_meta( 'linkedin' ) ) : ?>
                                    <a href="<?php echo esc_url( get_the_author_meta( 'linkedin' ) ); ?>" target="_blank" class="post-article__author-bio-social-link" title="Connect on LinkedIn"><i class="fab fa-linkedin"></i></a>
                                <?php elseif ( get_the_author_meta( 'twitter' ) ) : ?>
                                    <a href="<?php echo esc_url( get_the_author_meta( 'twitter' ) ); ?>" target="_blank" class="post-article__author-bio-social-link" title="Follow on Twitter"><i class="fab fa-twitter"></i></a>
                                <?php endif; ?>
                                
                                <!-- Second: CV Link -->
                                <a href="/cv/" target="_blank" class="post-article__author-bio-social-link" title="View CV & Portfolio">
                                    <i class="fas fa-file-alt"></i>
                                </a>
                                
                                <!-- Third: GitHub -->
                                <?php if ( get_the_author_meta( 'github' ) ) : ?>
                                    <a href="<?php echo esc_url( get_the_author_meta( 'github' ) ); ?>" target="_blank" class="post-article__author-bio-social-link" title="View GitHub Profile"><i class="fab fa-github"></i></a>
                                <?php else : ?>
                                    <!-- Fallback GitHub link if no author meta -->
                                    <?php if ( function_exists('site_config') && site_config('social.github') ) : ?>
                                        <a href="<?php echo esc_url( site_config('social.github') ); ?>" target="_blank" class="post-article__author-bio-social-link" title="View GitHub Profile"><i class="fab fa-github"></i></a>
                                    <?php endif; ?>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </aside>
            </div>
            
            <nav class="post-article__navigation">
                <?php
                the_post_navigation(
                    array(
                        'prev_text' => '<span class="nav-subtitle">' . esc_html__( 'Previous:', 'wp-modern-starter' ) . '</span> <span class="nav-title">%title</span>',
                        'next_text' => '<span class="nav-subtitle">' . esc_html__( 'Next:', 'wp-modern-starter' ) . '</span> <span class="nav-title">%title</span>',
                    )
                );
                ?>
            </nav>
        </div>
    </div>
</article>

<section class="post-actions">
    <div class="container">
        <div class="post-actions__wrapper">
            <div class="post-actions__social-share">
                <span class="post-actions__social-share-label"><?php esc_html_e( 'Share this article:', 'wp-modern-starter' ); ?></span>
                <div class="post-actions__share-buttons">
                    <button class="post-actions__share-btn post-actions__share-btn--twitter" data-url="<?php echo esc_url( get_permalink() ); ?>" data-title="<?php echo esc_attr( get_the_title() ); ?>">
                        <i class="fab fa-twitter"></i>
                    </button>
                    <button class="post-actions__share-btn post-actions__share-btn--facebook" data-url="<?php echo esc_url( get_permalink() ); ?>">
                        <i class="fab fa-facebook"></i>
                    </button>
                    <button class="post-actions__share-btn post-actions__share-btn--linkedin" data-url="<?php echo esc_url( get_permalink() ); ?>" data-title="<?php echo esc_attr( get_the_title() ); ?>">
                        <i class="fab fa-linkedin"></i>
                    </button>
                    <button class="post-actions__share-btn post-actions__share-btn--copy" data-url="<?php echo esc_url( get_permalink() ); ?>">
                        <i class="fas fa-link"></i>
                    </button>
                </div>
            </div>
        </div>
    </div>
</section>